---
title: "Oral Presentation"
---

## Purpose

The goal of this assignment is to help you practice your oral and visual communication skills and will be an opportunity to receive feedback on your research design. Presenting research is something that academics do all the time to publicize their work and to receive feedback from their peers.

## Task

Prepare and deliver a presentation. Your presentation should be between 10-12 minutes and make use of slides. There will be about five minutes for questions from your peers.


Your research presentations will take place during the week of May 5. 


## Organization of the Presentation

Your presentation must include the following sections:

1. Motivation: use an example that shows why your question matters or some interesting data that captures the audience's attention

2. Research Question: this may come before or after the literature review (whatever you think works best in the flow of the presentation)

3. Literature Review: tell us what we know and what we don't know in a couple of slides.

4. Theory

5. Research Design

6. Implications and Conclusion


## Criteria for Success

A successful research presentation will:

1. Present a clear research question toward the beginning
2. State what the researcher is trying to accomplish
3. Provide scholarly context for the research question (i.e., literature review)
4. Sufficiently explain all relevant concepts and how they connect
5. Include only necessary information in the slides (don't overcrowd them)
6. Use appropriate pace and tone




