---
title: "Peer Review for campaign memo"
---

# Purpose

Peer review is not only essential in the scientific community to check one another's work, but it can also be a great tool in your own learning process. Doing peer review turns you into a serious reader who is trying to understand the main thesis of a piece of writing as well as the arguments. The goal is to provide feedback to help the writer convey their argument in a clear and concise manner.


# Guidelines

As you read one another's work, I want you to be ***constructively ruthless*** and ***nice***. These terms are not mutually exclusive. Point out what is well done and areas for improvement (organization, formatting, missing information, unsupported conclusions, etc.). You can use the following questions as a guide to evaluate the draft:

1. Does the memo provide clear takeaways on the first page?
2. Is the purpose of the memo clear?
3. Does the memo describe the demographic characteristics of the state and of the Latine population?
4. Given the characteristics of the candidate, does the memo provide an answer to whether and how the candidate should reach out to potential voters?
5. Does the memo provide clear, actionable strategies for the campaign staff?
6. Does the memo use data and appropriately cite sources (e.g., using footnotes)?
7. Does the memo provide sufficient information without overwhelming the reader?
8. Does the memo's organization help effectively communicate the main points?
9. Does the memo use headers in a clear way? Are the paragraphs single spaced? Is there space between paragraphs? Does the memo use lists and bullet points appropriately?


You can also ask these questions of your own work. In fact, these are the same questions I'll be thinking about when I grade the memos.

